/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/bookings.ts
// Variable: BOOKINGS_BY_HOST_QUERY
// Query: *[  _type == "booking"  && host._ref == $hostId] | order(startTime asc) {  _id,  _type,  guestName,  guestEmail,  startTime,  endTime,  notes,  googleEventId,  meetLink}
export type BOOKINGS_BY_HOST_QUERYResult = Array<never>;
// Variable: BOOKINGS_IN_RANGE_QUERY
// Query: *[  _type == "booking"  && host._ref == $hostId  && startTime >= $startDate  && startTime <= $endDate] | order(startTime asc) {  _id,  startTime,  endTime,  googleEventId,  guestEmail}
export type BOOKINGS_IN_RANGE_QUERYResult = Array<never>;
// Variable: BOOKING_BY_ID_QUERY
// Query: *[  _type == "booking"  && _id == $bookingId][0]{  _id,  _type,  host->{    _id,    name,    email  },  guestName,  guestEmail,  startTime,  endTime,  notes,  googleEventId,  meetLink}
export type BOOKING_BY_ID_QUERYResult = null;
// Variable: BOOKING_WITH_HOST_CALENDAR_QUERY
// Query: *[  _type == "booking"  && _id == $bookingId][0]{  _id,  googleEventId,  host->{    _id,    connectedAccounts[isDefault == true][0]{      _key,      accountId,      email,      accessToken,      refreshToken,      expiryDate,      isDefault    }  }}
export type BOOKING_WITH_HOST_CALENDAR_QUERYResult = null;
// Variable: HOST_BOOKINGS_BY_CLERK_ID_QUERY
// Query: *[  _type == "booking"  && host->clerkId == $clerkId] | order(startTime asc) {  _id,  _type,  guestName,  guestEmail,  startTime,  endTime,  notes,  googleEventId,  meetLink}
export type HOST_BOOKINGS_BY_CLERK_ID_QUERYResult = Array<never>;
// Variable: HOST_UPCOMING_BOOKINGS_QUERY
// Query: *[  _type == "booking"  && host->clerkId == $clerkId  && startTime >= $startDate] | order(startTime asc) {  _id,  guestName,  guestEmail,  startTime,  endTime,  googleEventId,  meetLink}
export type HOST_UPCOMING_BOOKINGS_QUERYResult = Array<never>;
// Variable: BOOKINGS_BY_HOST_SLUG_IN_RANGE_QUERY
// Query: *[  _type == "booking"  && host->slug.current == $hostSlug  && startTime >= $startDate  && startTime <= $endDate] | order(startTime asc) {  _id,  startTime,  endTime}
export type BOOKINGS_BY_HOST_SLUG_IN_RANGE_QUERYResult = Array<never>;
// Variable: ALL_BOOKINGS_BY_HOST_SLUG_QUERY
// Query: *[  _type == "booking"  && host->slug.current == $hostSlug] | order(startTime asc) {  _id,  startTime,  endTime,  googleEventId,  guestEmail}
export type ALL_BOOKINGS_BY_HOST_SLUG_QUERYResult = Array<never>;

// Source: ./sanity/queries/meetingTypes.ts
// Variable: MEETING_TYPES_BY_HOST_QUERY
// Query: *[  _type == "meetingType"  && host->clerkId == $clerkId] | order(isDefault desc, name asc) {  _id,  name,  "slug": slug.current,  duration,  description,  isDefault}
export type MEETING_TYPES_BY_HOST_QUERYResult = Array<never>;
// Variable: MEETING_TYPE_BY_SLUGS_QUERY
// Query: *[  _type == "meetingType"  && host->slug.current == $hostSlug  && slug.current == $meetingTypeSlug][0] {  _id,  name,  "slug": slug.current,  duration,  description,  host-> {    _id,    name,    email,    "slug": slug.current,    availability[] {      _key,      startDateTime,      endDateTime    },    connectedAccounts[] {      _key,      accountId,      email,      isDefault,      accessToken,      refreshToken,      expiryDate    }  }}
export type MEETING_TYPE_BY_SLUGS_QUERYResult = null;
// Variable: MEETING_TYPES_BY_HOST_SLUG_QUERY
// Query: *[  _type == "meetingType"  && host->slug.current == $hostSlug] | order(isDefault desc, name asc) {  _id,  name,  "slug": slug.current,  duration,  description,  isDefault}
export type MEETING_TYPES_BY_HOST_SLUG_QUERYResult = Array<never>;
// Variable: HOST_ID_BY_CLERK_ID_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]._id
export type HOST_ID_BY_CLERK_ID_QUERYResult = null;

// Source: ./sanity/queries/users.ts
// Variable: USER_BY_CLERK_ID_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id,  _type,  clerkId,  name,  email,  slug,  availability[]{    _key,    startDateTime,    endDateTime  },  connectedAccounts[]{    _key,    accountId,    email,    provider,    isDefault,    connectedAt  }}
export type USER_BY_CLERK_ID_QUERYResult = null;
// Variable: USER_BY_SLUG_QUERY
// Query: *[  _type == "user"  && slug.current == $slug][0]{  _id,  _type,  name,  email,  slug,  availability[]{    _key,    startDateTime,    endDateTime  }}
export type USER_BY_SLUG_QUERYResult = null;
// Variable: USER_WITH_TOKENS_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id,  connectedAccounts[]{    _key,    accountId,    email,    accessToken,    refreshToken,    expiryDate,    isDefault  }}
export type USER_WITH_TOKENS_QUERYResult = null;
// Variable: USER_ID_BY_ACCOUNT_KEY_QUERY
// Query: *[  _type == "user"  && defined(connectedAccounts[_key == $accountKey])][0]{  _id}
export type USER_ID_BY_ACCOUNT_KEY_QUERYResult = null;
// Variable: USER_ID_BY_CLERK_ID_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id}
export type USER_ID_BY_CLERK_ID_QUERYResult = null;
// Variable: USER_WITH_AVAILABILITY_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id,  availability[]{    _key,    startDateTime,    endDateTime  }}
export type USER_WITH_AVAILABILITY_QUERYResult = null;
// Variable: USER_WITH_CONNECTED_ACCOUNTS_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id,  connectedAccounts[]{    accountId  }}
export type USER_WITH_CONNECTED_ACCOUNTS_QUERYResult = null;
// Variable: HOST_BY_SLUG_WITH_TOKENS_QUERY
// Query: *[  _type == "user"  && slug.current == $slug][0]{  _id,  name,  email,  slug,  availability[]{    _key,    startDateTime,    endDateTime  },  connectedAccounts[]{    _key,    accountId,    email,    accessToken,    refreshToken,    expiryDate,    isDefault  }}
export type HOST_BY_SLUG_WITH_TOKENS_QUERYResult = null;
// Variable: USER_CONNECTED_ACCOUNTS_DISPLAY_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  connectedAccounts[]{    _key,    accountId,    email,    isDefault  }}
export type USER_CONNECTED_ACCOUNTS_DISPLAY_QUERYResult = null;
// Variable: USER_SLUG_QUERY
// Query: *[  _type == "user"  && clerkId == $clerkId][0]{  _id,  name,  slug}
export type USER_SLUG_QUERYResult = null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[\n  _type == \"booking\"\n  && host._ref == $hostId\n] | order(startTime asc) {\n  _id,\n  _type,\n  guestName,\n  guestEmail,\n  startTime,\n  endTime,\n  notes,\n  googleEventId,\n  meetLink\n}": BOOKINGS_BY_HOST_QUERYResult;
    "*[\n  _type == \"booking\"\n  && host._ref == $hostId\n  && startTime >= $startDate\n  && startTime <= $endDate\n] | order(startTime asc) {\n  _id,\n  startTime,\n  endTime,\n  googleEventId,\n  guestEmail\n}": BOOKINGS_IN_RANGE_QUERYResult;
    "*[\n  _type == \"booking\"\n  && _id == $bookingId\n][0]{\n  _id,\n  _type,\n  host->{\n    _id,\n    name,\n    email\n  },\n  guestName,\n  guestEmail,\n  startTime,\n  endTime,\n  notes,\n  googleEventId,\n  meetLink\n}": BOOKING_BY_ID_QUERYResult;
    "*[\n  _type == \"booking\"\n  && _id == $bookingId\n][0]{\n  _id,\n  googleEventId,\n  host->{\n    _id,\n    connectedAccounts[isDefault == true][0]{\n      _key,\n      accountId,\n      email,\n      accessToken,\n      refreshToken,\n      expiryDate,\n      isDefault\n    }\n  }\n}": BOOKING_WITH_HOST_CALENDAR_QUERYResult;
    "*[\n  _type == \"booking\"\n  && host->clerkId == $clerkId\n] | order(startTime asc) {\n  _id,\n  _type,\n  guestName,\n  guestEmail,\n  startTime,\n  endTime,\n  notes,\n  googleEventId,\n  meetLink\n}": HOST_BOOKINGS_BY_CLERK_ID_QUERYResult;
    "*[\n  _type == \"booking\"\n  && host->clerkId == $clerkId\n  && startTime >= $startDate\n] | order(startTime asc) {\n  _id,\n  guestName,\n  guestEmail,\n  startTime,\n  endTime,\n  googleEventId,\n  meetLink\n}": HOST_UPCOMING_BOOKINGS_QUERYResult;
    "*[\n  _type == \"booking\"\n  && host->slug.current == $hostSlug\n  && startTime >= $startDate\n  && startTime <= $endDate\n] | order(startTime asc) {\n  _id,\n  startTime,\n  endTime\n}": BOOKINGS_BY_HOST_SLUG_IN_RANGE_QUERYResult;
    "*[\n  _type == \"booking\"\n  && host->slug.current == $hostSlug\n] | order(startTime asc) {\n  _id,\n  startTime,\n  endTime,\n  googleEventId,\n  guestEmail\n}": ALL_BOOKINGS_BY_HOST_SLUG_QUERYResult;
    "*[\n  _type == \"meetingType\"\n  && host->clerkId == $clerkId\n] | order(isDefault desc, name asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  duration,\n  description,\n  isDefault\n}": MEETING_TYPES_BY_HOST_QUERYResult;
    "*[\n  _type == \"meetingType\"\n  && host->slug.current == $hostSlug\n  && slug.current == $meetingTypeSlug\n][0] {\n  _id,\n  name,\n  \"slug\": slug.current,\n  duration,\n  description,\n  host-> {\n    _id,\n    name,\n    email,\n    \"slug\": slug.current,\n    availability[] {\n      _key,\n      startDateTime,\n      endDateTime\n    },\n    connectedAccounts[] {\n      _key,\n      accountId,\n      email,\n      isDefault,\n      accessToken,\n      refreshToken,\n      expiryDate\n    }\n  }\n}": MEETING_TYPE_BY_SLUGS_QUERYResult;
    "*[\n  _type == \"meetingType\"\n  && host->slug.current == $hostSlug\n] | order(isDefault desc, name asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  duration,\n  description,\n  isDefault\n}": MEETING_TYPES_BY_HOST_SLUG_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]._id": HOST_ID_BY_CLERK_ID_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id,\n  _type,\n  clerkId,\n  name,\n  email,\n  slug,\n  availability[]{\n    _key,\n    startDateTime,\n    endDateTime\n  },\n  connectedAccounts[]{\n    _key,\n    accountId,\n    email,\n    provider,\n    isDefault,\n    connectedAt\n  }\n}": USER_BY_CLERK_ID_QUERYResult;
    "*[\n  _type == \"user\"\n  && slug.current == $slug\n][0]{\n  _id,\n  _type,\n  name,\n  email,\n  slug,\n  availability[]{\n    _key,\n    startDateTime,\n    endDateTime\n  }\n}": USER_BY_SLUG_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id,\n  connectedAccounts[]{\n    _key,\n    accountId,\n    email,\n    accessToken,\n    refreshToken,\n    expiryDate,\n    isDefault\n  }\n}": USER_WITH_TOKENS_QUERYResult;
    "*[\n  _type == \"user\"\n  && defined(connectedAccounts[_key == $accountKey])\n][0]{\n  _id\n}": USER_ID_BY_ACCOUNT_KEY_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id\n}": USER_ID_BY_CLERK_ID_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id,\n  availability[]{\n    _key,\n    startDateTime,\n    endDateTime\n  }\n}": USER_WITH_AVAILABILITY_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id,\n  connectedAccounts[]{\n    accountId\n  }\n}": USER_WITH_CONNECTED_ACCOUNTS_QUERYResult;
    "*[\n  _type == \"user\"\n  && slug.current == $slug\n][0]{\n  _id,\n  name,\n  email,\n  slug,\n  availability[]{\n    _key,\n    startDateTime,\n    endDateTime\n  },\n  connectedAccounts[]{\n    _key,\n    accountId,\n    email,\n    accessToken,\n    refreshToken,\n    expiryDate,\n    isDefault\n  }\n}": HOST_BY_SLUG_WITH_TOKENS_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  connectedAccounts[]{\n    _key,\n    accountId,\n    email,\n    isDefault\n  }\n}": USER_CONNECTED_ACCOUNTS_DISPLAY_QUERYResult;
    "*[\n  _type == \"user\"\n  && clerkId == $clerkId\n][0]{\n  _id,\n  name,\n  slug\n}": USER_SLUG_QUERYResult;
  }
}
